#  █████╗ ██╗   ██╗████████╗ ██████╗ ███████╗████████╗ █████╗ ██████╗ ████████╗
# ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
# ███████║██║   ██║   ██║   ██║   ██║███████╗   ██║   ███████║██████╔╝   ██║   
# ██╔══██║██║   ██║   ██║   ██║   ██║╚════██║   ██║   ██╔══██║██╔══██╗   ██║   
# ██║  ██║╚██████╔╝   ██║   ╚██████╔╝███████║   ██║   ██║  ██║██║  ██║   ██║   
# ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   
                                                                             
#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗                               
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝                               
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗                              
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║                              
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝                              
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝                                          

exec-once = paplay ~/Sounds/start.mp3

#Wallpapers start
exec-once = hyprpaper &


exec-once = waybar
exec-once = swaync
exec-once = otd-daemon

