

# ██╗  ██╗███████╗██╗     ██╗      ██████╗ ██████╗                   
# ╚██╗██╔╝██╔════╝██║     ██║     ██╔═══██╗██╔══██╗                  
#  ╚███╔╝ █████╗  ██║     ██║     ██║   ██║██████╔╝                  
#  ██╔██╗ ██╔══╝  ██║     ██║     ██║   ██║██╔══██╗                  
# ██╔╝ ██╗███████╗███████╗███████╗╚██████╔╝██║  ██║                  
# ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝                  
                                                                   
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
                                                                   
#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗                     
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝                     
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗                    
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║                    
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝                    
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝                     
                                                                   


# https://wiki.hyprland.org/Configuring/

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/decorations.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/autostart.conf

debug {
    overlay = false
    damage_blink = false
}
