
# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗███████╗                         
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║██╔════╝                         
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║███████╗                         
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║╚════██║                         
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝███████║                         
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚══════╝                         
                                                                                   
#  █████╗ ███╗   ██╗██████╗                                                          
# ██╔══██╗████╗  ██║██╔══██╗                                                         
# ███████║██╔██╗ ██║██║  ██║                                                         
# ██╔══██║██║╚██╗██║██║  ██║                                                         
# ██║  ██║██║ ╚████║██████╔╝                                                         
# ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝                                                          
                                                                                   
# ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗███████╗██████╗  █████╗  ██████╗███████╗███████╗
# ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝
# ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ ███████╗██████╔╝███████║██║     █████╗  ███████╗
# ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝  ╚════██║
# ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗███████║██║     ██║  ██║╚██████╗███████╗███████║
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝
                                                                                   

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
windowrule = float, ^(kitty)$
windowrule = float, ^(qpwgraph)$
windowrulev2 = float, class:^(translator\.py)$
windowrulev2 = move center, class:^(translator\.py)$
windowrulev2 = move center, title:^(Translator with Auto-Detect)$




# Example windowrule v2
windowrulev2 = size 1000 500,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0




workspace = 1,on-created-empty:[c] obsidian
workspace = 2,on-created-empty:[c] zen-browser
workspace = 3,on-created-empty:[c] code
workspace = 4,on-created-empty:[c] vesktop  
workspace = 5,on-created-empty:[c] telegram-desktop
layerrule = blur, waybar
layerrule = blur, rofi
layerrule = blur, swaync-client
